### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by peter279k** [beryllium/cache#1]
As title, is this project still under maintained?

**Comment by beryllium** [comment]
I haven't done any work on it lately. It was my understanding that [PSR-16](https://www.php-fig.org/psr/psr-16/) would mean that most other caching libraries would be able to ship a SimpleCache interface, rendering my own lib unnecessary. I'm not sure if that has happened, though.

**Comment by peter279k** [comment]
Hi @beryllium, thanks for your reply.

If possible, let me contribute some codes on this repository :smile:.

**Comment by beryllium** [comment]
PRs welcome :) I just updated master to require PHP >= 7.2.0 and use PHPUnit > 8.3, in preparation for new contributions to go under a "2.0.0" release.

**Comment by beryllium** [comment]
I've just pushed `2.0.0-alpha1` for this library, which includes a bunch of improvements and changes.

**Comment by peter279k** [comment]
Just close this issue because this project is still maintained.
